environment:
    TARGET: 1.12.0-x86_64-pc-windows-gnu
    MSYS2_BITS: 64
install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
    - rust-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
    - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
    - rustc -V
    - cargo -V

build_script:
    - cargo build --release
    - cargo build

artifacts:
    - path: target\release\mymdb.exe
      name: release

    - path: target\debug\mymdb.exe
      name: debug

cache:
    - C:\Users\appveyor\.cargo
