# environment:
    # TARGET: 1.10.0-x86_64-pc-windows-gnu
    # MSYS2_BITS: 64
# install:
    # - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
    # - rust-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    # - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
    # - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
    # - rustc -V
    # - cargo -V
# 
# build_script:
    # - cargo build --release
    # - cargo build
# 
# test_script:
    # - cargo test
# 
# artifacts:
    # - path: target\release\stones.exe
      # name: release
# 
    # - path: target\debug\stones.exe
      # name: debug
# 
# cache:
    # - C:\Users\appveyor\.cargo

os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

artifacts:
  - path: target\release\stones.exe
    name: release

test_script:
  - cargo test --verbose

